groups:
  md_5:
    - admin

connection_throttle: -1  # Prevents connection issues
connection_throttle_limit: 3
online_mode: false       # Required for Eaglercraft compatibility
remote_ping_timeout: 5000
remote_ping_cache: -1
timeout: 30000
ip_forward: true        # Ensures correct player IPs and UUIDs
forge_support: false
player_limit: -1
max_packets_per_second: 4096
max_packets_data_per_second: 3.3554432E7
log_pings: true
log_commands: false
reject_transfers: false
prevent_proxy_connections: true  # Security: Prevents unauthorized proxy usage
server_connect_timeout: 5000
enforce_secure_profile: false    # Allows offline-mode players

servers:
  lobby:
    # Update the address to the public endpoint of your Spigot server.
    # Ensure that this address (responsible-lonna-sigmasfromohio-bfb48e6e.koyeb.app) is accessible on port 25565
    address: responsible-lonna-sigmasfromohio-bfb48e6e.koyeb.app:25565
    motd: '&1Welcome to the Eaglercraft Network'
    restricted: false

listeners:
  - bind_local_address: true
    force_default_server: true
    forced_hosts:
      pvp.md-5.net: pvp
    # BungeeCord listens for incoming client connections on this address/port.
    host: 0.0.0.0:25565
    max_players: 100
    motd: '&1Eaglercraft Bungee Server'
    ping_passthrough: false
    priorities:
      - lobby
    proxy_protocol: false
    query_enabled: false
    query_port: 25577
    tab_list: GLOBAL_PING
    tab_size: 60

permissions:
  admin:
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.reload
    - bungeecord.command.kick
    - bungeecord.command.send
    - bungeecord.command.find
  default:
    - bungeecord.command.server
    - bungeecord.command.list

disabled_commands:
  - disabledcommandhere
