groups:
  md_5:
  - admin
connection_throttle: 4000
connection_throttle_limit: 3
online_mode: false
remote_ping_timeout: 5000
servers:
  lobby:
    address: localhost:25565
    motd: '&1Welcome to the Eaglercraft Network'
    restricted: false
remote_ping_cache: -1
enforce_secure_profile: false
timeout: 30000
ip_forward: false  # Ensures correct player IPs and UUIDs
forge_support: false
player_limit: -1
max_packets_per_second: 4096
disabled_commands:
- disabledcommandhere
log_pings: true
max_packets_data_per_second: 3.3554432E7
log_commands: false
stats: 84ac5074-2d87-408c-b0a4-f30294cd50b8
listeners:
- bind_local_address: true
  force_default_server: true
  forced_hosts:
    pvp.md-5.net: pvp
  host: 0.0.0.0:28732  # Ensure this matches your server port
  max_players: 100  # Adjust based on your server capacity
  motd: '&1Eaglercraft Bungee Server'
  ping_passthrough: false
  priorities:
  - lobby
  proxy_protocol: false
  query_enabled: false
  query_port: 25577
  tab_list: GLOBAL_PING
  tab_size: 60
reject_transfers: false
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
  - bungeecord.command.send
  - bungeecord.command.find
  default:
  - bungeecord.command.server
  - bungeecord.command.list
prevent_proxy_connections: true  # Security: Prevents unauthorized proxy usage
server_connect_timeout: 5000
